
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inbound-tx
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-hub
spec:
  config:
    retention.ms: 10000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inbound-ack
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-hub
spec:
  config:
    retention.ms: 10000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: outbound-ack
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-hub
spec:
  config:
    retention.ms: 10000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: outbound-processed
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-hub
spec:
  config:
    retention.ms: 30000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: valid-payments
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-hub
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: invalid-transactions
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-hub
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: invalid-acks
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-hub
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3