---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: payment-kafka
  namespace: payment-infra
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.8'
      inter.broker.protocol.version: '2.8'
    version: 2.8.0
    storage:
      type: ephemeral
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      type: ephemeral
    replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inbound-tx
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-infra
spec:
  config:
    retention.ms: 10000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3

---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inbound-ack
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-infra
spec:
  config:
    retention.ms: 10000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: outbound-ack
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-infra
spec:
  config:
    retention.ms: 10000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: outbound-processed
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-infra
spec:
  config:
    retention.ms: 30000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: valid-payments
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-infra
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: invalid-payments
  labels:
    strimzi.io/cluster: payment-kafka
  namespace: payment-infra
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3