oc -n kafka run kafka-producer \
    -ti --image=quay.io/strimzi/kafka:latest-kafka-2.7.0 --rm=true \
    --restart=Never -- bin/kafka-console-producer.sh \
    --broker-list payment-kafka-kafka-bootstrap.payment-infra.svc:9092  --topic invalid-acks

    mvn clean package -DskipTests -Dquarkus.native.container-build=true -Dquarkus.kubernetes-client.trust-certs=true -Dquarkus.container-image.build=true -Pnative   

    
    
    kn source kafka create invalid-ack --servers payment-kafka-kafka-bootstrap.payment-hub.svc:9092 --topics invalid-acks --consumergroup ack-serverless --sink process-failed-acks